### ISSUE TITLE
no ships and no ability to claim the staked kyanite when logging in-chrome MM issue

### ISSUE THREAD

**Issue by Kripto-hub** [onikamigames/starshipgame#138]
I went step by step on the guide but I got the same problem some other people are reporting.  I don't have ships and i can't claim my staked kyanite at the start.  I use chrome and the MM plugin, my anchor wallet is set up and I have my NFTs and can see those but it gives the player account not found error. 
I did check and other GitHub folks are reporting but no workaround for it. some report they got it working but give no clue how they did it.  Also yes I have more than $10 in SS token
My Wax testnet is togatoga4321

**Comment by onikamigames** [comment]
Fixed! Could you check your hangar a close this issue?

Thanks!

**Comment by Kripto-hub** [comment]
still no luck.  I cleared the connections in MM 
and Anchor as well as tried with the Firewall turned off and still nothing
. can you check it again?
